language: java
jdk:
  - openjdk11

install: true

script:
  - ./mvnw clean install org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report -Dmaven.javadoc.skip=true -Pall #sonar:sonar -Dsonar.projectKey=bxbot -Dsonar.organization=barrybecker4

# This keeps giving unauthorized, so disabling for now
#addons:
#  sonarcloud:
#    organization: "barrybecker4"
#    token:
#      secure: "BNS3qepEhjSCOarbFqLINbR2e2drNwAthXRZOf2XGP90QVBu3hUoPrdT3SGFEQjt6KXjkh8d1pETKgKvsyk33pDoCNHsIpZyFz6AsHY3xO6chJv4MjvReUgJD1+FZ2msdTe2pwdUP9osrfcJUoI6FWt72eUuaSEuYBfBVZe9GpDr+02yXz3TQjope4MCzaALZ1sZjVmPy09Un7cdg8oREkBvhw7Qi1QFn5ifVK0UbYKnDeK3Lgu/nKReM9THT9X1Au5o5SPvGOHt/U79NcyNTeC9nRvv9jPYDQ63xIrmS4pFAVjiikJRE7hXA9bjWxDuK5DDeGo2qfToJdPEYN2PsoCp2uNW0aTevxgPUZrj8L8WkZdIHAJ6QuI78UgahYXKDVvx9qPh87oJ4qNYVJuQm5Afe621hqBi4rMbK0vbnoZkTnatBENSFY45Emp49JdNfsKZfVyQBxb8lh7N7lJNG9X2tyP23XiJkUHr3dIyNynCEsxKJPs417t2wxaxURL5f3IL6Z//fRpUu7DQFV9ufokPkGe7tEMvIcsWG0xshMsujN/E2DcxOHTSbGNa6WHtCEwNyJboyT0pdVTuFAJpd6aCB5Jb7lwaubCuzXmwcoWbcwDoMbT6p48B3hws8h9f5DPvAJb/sRQikufgkNfpfiFHhU2ygm9LDoT+6wPH3Mo="

